### ISSUE TITLE
Telemetry decoder doesn't parse not full value frames.

### ISSUE THREAD

**Issue by ogor89** [hessu/perl-aprs-fap#6]
As mentioned here:
https://github.com/PhirePhly/aprs_notes/blob/master/telemetry_format.md
"Stations are not required to use all five analog and the binary field."
But telemetry parser interpretes them as "Invalid telemetry packet".
Example:
CALL-3>APRS, ... :T#021,028,028 [Invalid telemetry packet]

**Comment by hessu** [comment]
Hi,

The actual specification (APRS101.PDF page 68, TELEMETRY DATA, Telemetry Report Format) does seem to indicate that all fields/commas need to be present, only the comment part is optional (gray background). For EQNS/PARM/UNIT packets it is specifically allowed that "The list can terminate after any field" but this is not the case for the telemetry data packet.

When implementing telemetry parsing I looked at an awful lot of incoming telemetry data, and whenever a telemetry channel was not used by a transmitter, it was either empty (",,") or zero. I specifically threw several days or weeks of data to the parser after modifications and new parser features, to see if a lot of packets were not parsed, and tried to figure out if others have deciphered the specification the same way I had. If there were widespread misreadings of the spec, I tried to allow those if possible.

I'm not greatly in favour of making this parser allow new relaxed variations of the specification, since if aprs.fi allows it and does not report issues, people implementing transmitters might think their packets are OK and then be upset when a lot of other parsers elsewhere are more strict about the spec.

That said, the telemetry parser *is* a bit relaxed already; it allows decimal values, negative values, and values outside the 0-255 range, since they were seen already when I was implementing the parser. The 8-bit resolution seemed outrageously limited.

Are you seeing a lot of packets like this, or is it just packets you're generating?

**Comment by hessu** [comment]
Ah, now when I read your link to Kenneth's notes, I find his *Proposed Telemetry format*, which I had already forgotten about, and which the parser does not implement. It'd be a good improvement over the APRS101.pdf spec, it might be good to discuss it on the APRSSIG and see if it could be approved a bit more widely and used instead of the APRS101.PDF spec.

**Comment by hessu** [comment]
The parser was updated in c924f5fe4bf8fc266b30ce3b40745842cae761e9 (year 2020) to implement Kenneth's proposed telemetry format, and this ticket is probably now addressed.
